title: "Aishwarya Swain"
bio: "A mountain lover, curious learner, and explorer at heart"
description: "A blog about technology and stuff related"
external-image: false
picture: "assets/images/profile.jpg"

dark-theme: false
resume: true
resume-external: true
resume-url: "https://google.com/?q=my+resume"

url: "https://aishwarya-swain.github.io"
baseurl: "/indigo"

permalink: /:title/

disqus:
  shortname: github
  categories:
    - blog
    - project

facebook: myfacebook
twitter: mytwitter
instagram: myinstagram
linkedin: mylinkedin
googlescholar: mygooglescholar
email: myemail@gmail.com

authors:
  aishwarya:
    name: "Aishwarya Swain"
    bio: "A mountain lover, curious learner, and explorer at heart"
    external-image: false
    picture: assets/images/profile.jpg
    twitter: bioaish
    
  aishwaryaswain:
    name: "Aishwarya1 Swain"
    bio: "coffee adict"
    external-image: false
    picture: assets/images/james.jpg
    twitter: bioaish

width: normal

projects: true
about: true
blog: true

read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true

defaults:
  - scope:
      path: ""
      layout: "post"
    values:
      hidden: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - FAQ.md
  - vendor
